# Generated by Django 4.2.4 on 2023-08-21 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trufas", "0002_sabor"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sabor",
            new_name="Sabores",
        ),
    ]
