# Generated by Django 4.2.4 on 2023-08-21 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trufas", "0003_rename_sabor_sabores"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sabores",
            new_name="Sabore",
        ),
    ]
