# Generated by Django 4.2.4 on 2023-08-21 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trufas", "0004_rename_sabores_sabore"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sabore",
            new_name="Sabor",
        ),
    ]
